### ISSUE TITLE
failed to exec: ENOENT: No such file or directory

### ISSUE THREAD

**Issue by baszalmstra** [novafacing/memfd-exec#10]
Thanks for this terrific library! I really like how much complexity it wraps!

Im trying to use this library on a variety of architectures. The code seems to work great for `x86_64` but panics on any other architecture I try to run it (`aarch64`, `arm`, `powerpc64`, `s390x`).

```
thread 'test::test_glibc_version' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/memfd-exec-0.2.1/src/executable.rs:350:13:
failed to exec: ENOENT: No such file or directory
stack backtrace:
   0: rust_begin_unwind
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/std/src/panicking.rs:645:5
   1: core::panicking::panic_fmt
             at /rustc/82e1608dfa6e0b5569232559e3d385fea5a93112/library/core/src/panicking.rs:72:14
   2: memfd_exec::executable::MemFdExecutable::spawn
   3: memfd_exec::executable::MemFdExecutable::output
```

Is this a limitation of the library? A bug? Or am I doing something wrong?

**Comment by baszalmstra** [comment]
Ah this also happens when the executable links to symbols that don't exist. Ideally instead of `panic`ing this crate would return the error.

**Comment by novafacing** [comment]
Yeah, this will be an error with the executed binary, not this crate (I think) but maybe checks can be added or propagate as a result/exit code like you mention.
