### ISSUE TITLE
MemFdExecutable takes a Vec<u8> instead of &[u8]

### ISSUE THREAD

**Issue by jean-airoldie** [novafacing/memfd-exec#3]
What is the specific reasoning behind `MemFdExecutable::new` taking a `Vec<u8>`? Looking at the code, it seems like it is used as a `&[u8]` when spawning the process anyway.

In my specific use case, this would force me to allocate a vector just for that purpose which is quite wasteful since statically linked executable tend to be on the bigger side.

**Comment by novafacing** [comment]
Yep, the specific reasoning is that I was not experienced when I wrote this!

Feel free to PR any changes you think make sense :)
